<Project>
	<PropertyGroup>
		<QueryWattVersion>0.1.0-preview.1</QueryWattVersion>
		<Version>$(QueryWattVersion)</Version>
		<InformationalVersion>$(QueryWattVersion)</InformationalVersion>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
</Project>