<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/QueryWatt.Baselines/QueryWatt.Baselines.csproj" />
    <ProjectReference Include="../../src/QueryWatt.Configuration/QueryWatt.Configuration.csproj" />
    <ProjectReference Include="../../src/QueryWatt.Core/QueryWatt.Core.csproj" />
    <ProjectReference Include="../../src/QueryWatt.SqlServer/QueryWatt.SqlServer.csproj" />
  </ItemGroup>
</Project>
